App\Entity\City:
    properties:
        name:
            - NotBlank:
                groups: ['create', 'edit']
        country:
            - NotBlank: 
                groups: ['create', 'edit']
            - Length:
                min: 2
                max: 2
                groups: ['create', 'edit']
        latitude:
            - NotBlank:
                groups: ['create', 'edit']
            - Range:
                min: -90
                max: 90
                groups: ['create', 'edit']
        longitude:
            - NotBlank:
                groups: ['create', 'edit']
            - Range:
                min: -180
                max: 180
                groups: ['create', 'edit']

App\Entity\Forecast:
    properties:
        temperature:
            - NotBlank:
                groups: ['create', 'edit']
            - Range:
                min: -60
                max: 60
                groups: ['create', 'edit']
        humidity:
            - NotBlank:
                groups: ['create', 'edit']
            - Range:
                min: 0
                max: 100
                groups: ['create', 'edit']
        weathercondition:
            - NotBlank:
                groups: ['create', 'edit']
        windspeed:
            - NotBlank:
                groups: ['create', 'edit']
            - Range:
                min: 0
                max: 410
                groups: ['create', 'edit']
        date:
            - NotBlank:
                groups: ['create', 'edit']
              
